// component tokens for halifax

export default {
  button: {
    colourPrimaryBackgroundDefault: '#005eb8',
    colourPrimaryBackgroundHover: '#071d49',
    colourPrimaryBackgroundPressed: '#005eb8',
    colourPrimaryBackgroundFocus: '#005eb8',
    colourPrimaryBackgroundDisabled: '#e1e4e9',
    colourPrimaryTextDefault: '#ffffff',
    colourPrimaryTextDisabled: '#596682',
    colourPrimaryBorderFocus: '#b67fca',
    colourSecondaryBackgroundDefault: '#ffffff',
    colourSecondaryBackgroundHover: '#e1e4e9',
    colourSecondaryBackgroundPressed: '#005eb8',
    colourSecondaryBackgroundFocus: '#ffffff',
    colourSecondaryBackgroundDisabled: '#b5bbc8',
    colourSecondaryTextDefault: '#005eb8',
    colourSecondaryTextHover: '#071d49',
    colourSecondaryTextDisabled: '#596682',
    colourSecondaryTextPressed: '#ffffff',
    colourSecondaryIconDefault: '#071d49',
    colourSecondaryBorderDefault: '#071d49',
    colourSecondaryBorderHover: '#071d49',
    colourSecondaryBorderFocus: '#b67fca',
    colourSecondaryBorderFocusInner: '#005eb8',
    colourTertiaryBackgroundDefault: '#ffffff',
    colourTertiaryBackgroundActive: '#005eb8',
    colourTertiaryBackgroundInverse: '#ffffff',
    colourTertiaryBorderDefault: '#071d49',
    colourTertiaryBorderActive: '#005eb8',
    radiusDefault: '4.000rem',
    radiusFocus: '4.000rem',
    spaceFocus: '0.313rem',
    sizeSmMinHeight: '3.000rem',
    typeMediumFontSize: '1.125rem',
    typeMediumLineHeight: '1.500rem',
    typeSmallFontSize: '1.000rem',
    typeSmallLineHeight: '1.250rem',
    typeTinyFontSize: '0.750rem',
    typeTinyLineHeight: '1.000rem',
    typeTagFontSize: '0.750rem',
    typeTagLineHeight: '1.000rem',
  },
  card: {
    borderDefault: '0',
    borderInverse: '0.063rem',
    spaceDefault: '1.500rem',
    spaceSmNegative: '0',
    spaceSmPositive: '1.000rem',
  },
  checkbox: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#ffffff',
    colourBackgroundDisabled: '#ffffff',
    colourBackgroundActiveDisabled: '#e1e4e9',
    colourBorderDefault: '#838ea4',
    colourBorderHover: '#071d49',
    colourBorderFocusInner: '#071d49',
    colourBorderFocusOuter: '#b67fca',
    colourBorderDisabled: '#838ea4',
    colourBorderDisabled2: '#b5bbc8',
    colourIconDefault: '#005eb8',
    colourIconDisabled: '#b5bbc8',
    borderDefault: '0.125rem',
    borderSelected: '0.125rem',
    borderFocusInner: '0.125rem',
    borderFocusOuter: '0.125rem',
    radiusDefault: '0.375rem',
    radiusFocus: '0.500rem',
  },
  chip: {
    colourBackgroundDefault: '#071d49',
    colourTextDefault: '#ffffff',
  },
  input: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundDim: '#e1e4e9',
    colourBackgroundHover: '#4698e8',
    colourBackgroundError: '#fae6ed',
    colourBackgroundDisabled: '#e1e4e9',
    colourBackgroundDisabled2: '#e1e4e9',
    colourTextInverse: '#ffffff',
    colourBorderDefault: '#838ea4',
    colourBorderSubdued: '#b5bbc8',
    colourBorderActive: '#071d49',
    colourBorderDisabled: '#e1e4e9',
    borderDefault: '0.125rem',
    borderActive: '0.125rem',
  },
  label: {
    colourBackgroundDefault: '#4698e8',
    colourTextDefault: '#ffffff',
  },
  masthead: {
    colourSurfaceBrand: '#005eb8',
    colourSurfaceBrand2: '#edf6ff',
    colourSurfaceBrand3: '#005eb8',
    colourSizeHelphubNavHeight: '4.500rem',
  },
  menu: {
    colourBackgroundDefault: '#071d49',
    colourTextDefault: '#ffffff',
    colourIconDefault: '#ffffff',
  },
  notification: {
    borderDefault: '0.125rem',
    radiusDefault: '0.500rem',
  },
  panel: {
    radiusDefault: '0',
  },
  progressStep: {
    colourBackgroundDefault: '#e1e4e9',
    colourBackgroundDefault2: '#b5bbc8',
    colourBackgroundDefault3: '#ffffff',
    colourBackgroundActive: '#24a973',
    colourBackgroundDashedLine: '#838ea4',
    colourTextComplete: '#071d49',
    colourTextCurrent: '#005eb8',
    colourTextRemaining: '#838ea4',
    borderMojaLbg: '0.063rem',
    borderInner: '0.375rem',
  },
  radio: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#005eb8',
    colourBackgroundDisabled: '#b5bbc8',
    colourRadioDefault: '#596682',
    colourRadioHover: '#071d49',
    colourRadioFocusInner: '#838ea4',
    colourRadioFocusOuter: '#b67fca',
    colourRadioDisabled: '#838ea4',
    colourRadioActiveDisabled: '#838ea4',
    borderDefault: '0.125rem',
    borderSelected: '0.125rem',
    borderFocusInner: '0.125rem',
    borderFocusOuter: '0.125rem',
  },
  selector: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#e1e4e9',
    colourBackgroundActive: '#ffffff',
    colourBackgroundActiveDisabled: '#edf6ff',
    colourBackgroundDisabled: '#e1e4e9',
    colourTextDefault: '#005eb8',
    colourTextActive: '#071d49',
    colourTextDisabled: '#838ea4',
    colourBorderDefault: '#b5bbc8',
    colourBorderDefault2: '#b5bbc8',
    colourBorderBrand: '#005eb8',
    colourBorderCurrent: '#b5bbc8',
    colourBorderDisabled: '#838ea4',
    colourBorderActive: '#005eb8',
    colourBorderActiveDisabled: '#071d49',
    borderDefault: '0.125rem',
    borderDefaultInverse: '0',
    borderUnselected: '0.125rem',
    typeSelector text: 'Semibold',
  },
  switch: {
    colourBackgroundInverse: '#ffffff',
    colourBackgroundBrand: '#005eb8',
    colourBackgroundSwitchOff: '#ffffff',
    colourBackgroundBackgroundOff: '#838ea4',
    colourBackgroundDisabled: '#e1e4e9',
    colourBackgroundActiveDisabled: '#edf6ff',
  },
  table: {
    colourBackgroundFixed: '#ffffff',
    colourBackgroundFixedSubtle: '#ffffff',
    colourBackgroundHeader: '#edf6ff',
    colourBackgroundActive: '#005eb8',
    colourBackgroundActiveSubdued: '#edf6ff',
    colourBackgroundActiveSubtle: '#edf6ff',
    colourTextDefault: '#000000',
    colourTextHeader: '#071d49',
    colourTextInverse: '#ffffff',
    colourTextActive: '#000000',
    colourBorderDefault1: '#005eb8',
    colourBorderDefault2: '#005eb8',
    colourBorderBrand: '#005eb8',
    colourBorderActive: '#005eb8',
  },
  tile: {
    sizeMinHeight: '12.625rem',
  },
  toggle: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundActive: '#071d49',
    colourTextDefault: '#005eb8',
    colourTextActive: '#ffffff',
    colourBorderDefault: '#838ea4',
    borderOuter: '0.125rem',
    borderOuterNone: '0',
    borderInner: '0.125rem',
    radiusInner: '4.000rem',
    radiusOuter: '4.000rem',
    spaceDefault: '0.250rem',
    typeToggle: 'Semibold',
  },
};