// component tokens for moja

export default {
  button: {
    colourPrimaryBackgroundDefault: '#27dcae',
    colourPrimaryBackgroundHover: '#5de5c2',
    colourPrimaryBackgroundPressed: '#27dcae',
    colourPrimaryBackgroundFocus: '#27dcae',
    colourPrimaryBackgroundDisabled: '#e6e6e6',
    colourPrimaryTextDefault: '#000000',
    colourPrimaryTextDisabled: '#767676',
    colourPrimaryBorderFocus: '#000000',
    colourSecondaryBackgroundDefault: '#ffffff',
    colourSecondaryBackgroundHover: '#f2f2f2',
    colourSecondaryBackgroundPressed: '#000000',
    colourSecondaryBackgroundFocus: '#ffffff',
    colourSecondaryBackgroundDisabled: '#e6e6e6',
    colourSecondaryTextDefault: '#000000',
    colourSecondaryTextHover: '#000000',
    colourSecondaryTextDisabled: '#767676',
    colourSecondaryTextPressed: '#ffffff',
    colourSecondaryIconDefault: '#000000',
    colourSecondaryBorderDefault: '#000000',
    colourSecondaryBorderHover: '#404040',
    colourSecondaryBorderFocus: '#000000',
    colourSecondaryBorderFocusInner: '#000000',
    colourTertiaryBackgroundDefault: '#ffffff',
    colourTertiaryBackgroundActive: '#068482',
    colourTertiaryBackgroundInverse: '#000000',
    colourTertiaryBorderDefault: '#000000',
    colourTertiaryBorderActive: '#068482',
    radiusDefault: '4.000rem',
    radiusFocus: '4.000rem',
    spaceFocus: '0',
    sizeSmMinHeight: '1.875rem',
    typeMediumFontSize: '1.000rem',
    typeMediumLineHeight: '1.500rem',
    typeSmallFontSize: '0.875rem',
    typeSmallLineHeight: '1.000rem',
    typeTinyFontSize: '0.750rem',
    typeTinyLineHeight: '1.000rem',
    typeTagFontSize: '0.750rem',
    typeTagLineHeight: '1.000rem',
  },
  card: {
    borderDefault: '0.063rem',
    borderInverse: '0',
    spaceDefault: '0',
    spaceSmNegative: '1.000rem',
    spaceSmPositive: '0',
  },
  checkbox: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#068482',
    colourBackgroundDisabled: '#ffffff',
    colourBackgroundActiveDisabled: '#82c1c0',
    colourBorderDefault: '#767676',
    colourBorderHover: '#068482',
    colourBorderFocusInner: '#068482',
    colourBorderFocusOuter: '#000000',
    colourBorderDisabled: '#bfbfbf',
    colourBorderDisabled2: '#82c1c0',
    colourIconDefault: '#ffffff',
    colourIconDisabled: '#ffffff',
    borderDefault: '0.125rem',
    borderSelected: '0.125rem',
    borderFocusInner: '0.125rem',
    borderFocusOuter: '0.125rem',
    radiusDefault: '0.250rem',
    radiusFocus: '0.375rem',
  },
  chip: {
    colourBackgroundDefault: '#3de0b7',
    colourTextDefault: '#000000',
  },
  input: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundDim: '#e6e6e6',
    colourBackgroundHover: '#068482',
    colourBackgroundError: '#fdeae9',
    colourBackgroundDisabled: '#f2f2f2',
    colourBackgroundDisabled2: '#f2f2f2',
    colourTextInverse: '#ffffff',
    colourBorderDefault: '#767676',
    colourBorderSubdued: '#bfbfbf',
    colourBorderActive: '#068482',
    colourBorderDisabled: '#f2f2f2',
    borderDefault: '0.063rem',
    borderActive: '0.125rem',
  },
  label: {
    colourBackgroundDefault: '#27dcae',
    colourTextDefault: '#000000',
  },
  masthead: {
    colourSurfaceBrand: '#27dcae',
    colourSurfaceBrand2: '#c9f6ea',
    colourSurfaceBrand3: '#000000',
    colourSizeHelphubNavHeight: '4.500rem',
  },
  menu: {
    colourBackgroundDefault: '#000000',
    colourTextDefault: '#ffffff',
    colourIconDefault: '#ffffff',
  },
  notification: {
    borderDefault: '0',
    radiusDefault: '0.750rem',
  },
  panel: {
    radiusDefault: '0',
  },
  progressStep: {
    colourBackgroundDefault: '#f2f2f2',
    colourBackgroundDefault2: '#e6e6e6',
    colourBackgroundDefault3: '#000000',
    colourBackgroundActive: '#27dcae',
    colourBackgroundDashedLine: '#27dcae',
    colourTextComplete: '#767676',
    colourTextCurrent: '#000000',
    colourTextRemaining: '#767676',
    borderMojaLbg: '0',
    borderInner: '0',
  },
  radio: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#068482',
    colourBackgroundDisabled: '#82c1c0',
    colourRadioDefault: '#767676',
    colourRadioHover: '#068482',
    colourRadioFocusInner: '#068482',
    colourRadioFocusOuter: '#27dcae',
    colourRadioDisabled: '#bfbfbf',
    colourRadioActiveDisabled: '#82c1c0',
    borderDefault: '0.125rem',
    borderSelected: '0.125rem',
    borderFocusInner: '0.125rem',
    borderFocusOuter: '0.125rem',
  },
  selector: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#f2f2f2',
    colourBackgroundActive: '#eafcf7',
    colourBackgroundActiveDisabled: '#f4fdfb',
    colourBackgroundDisabled: '#f2f2f2',
    colourTextDefault: '#000000',
    colourTextActive: '#000000',
    colourTextDisabled: '#bfbfbf',
    colourBorderDefault: '#ffffff',
    colourBorderDefault2: '#ffffff',
    colourBorderBrand: '#27dcae',
    colourBorderCurrent: '#bfbfbf',
    colourBorderDisabled: '#f2f2f2',
    colourBorderActive: '#068482',
    colourBorderActiveDisabled: '#82c1c0',
    borderDefault: '0.125rem',
    borderDefaultInverse: '0.125rem',
    borderUnselected: '0',
    typeSelector text: 'Regular',
  },
  switch: {
    colourBackgroundInverse: '#ffffff',
    colourBackgroundBrand: '#068482',
    colourBackgroundSwitchOff: '#ffffff',
    colourBackgroundBackgroundOff: '#767676',
    colourBackgroundDisabled: '#e6e6e6',
    colourBackgroundActiveDisabled: '#82c1c0',
  },
  table: {
    colourBackgroundFixed: '#ffffff',
    colourBackgroundFixedSubtle: '#e6e6e6',
    colourBackgroundHeader: '#1a1a1a',
    colourBackgroundActive: '#068482',
    colourBackgroundActiveSubdued: '#eafcf7',
    colourBackgroundActiveSubtle: '#eafcf7',
    colourTextDefault: '#000000',
    colourTextHeader: '#ffffff',
    colourTextInverse: '#ffffff',
    colourTextActive: '#000000',
    colourBorderDefault1: '#767676',
    colourBorderDefault2: '#767676',
    colourBorderBrand: '#27dcae',
    colourBorderActive: '#068482',
  },
  tile: {
    sizeMinHeight: '11.375rem',
  },
  toggle: {
    colourBackgroundDefault: '#f2f2f2',
    colourBackgroundActive: '#068482',
    colourTextDefault: '#767676',
    colourTextActive: '#ffffff',
    colourBorderDefault: '#ffffff',
    borderOuter: '0',
    borderOuterNone: '0',
    borderInner: '0',
    radiusInner: '4.000rem',
    radiusOuter: '4.000rem',
    spaceDefault: '0',
    typeToggle: 'Bold',
  },
};