// typography tokens for moja

export default {
  font: {
    familyPrimary: 'Bebas Neue',
    familySecondary: 'Lato',
    weightHeadingPrimary: 'Regular',
    weightBodyPrimary: 'Regular',
    weightBodyAlt1: 'SemiBold',
    weightBodyAlt2: 'Bold',
  },
  textStyle: {
    titleFontSize: '1.250rem',
    titleLineHeight: '1.250rem',
    titleHugeFontSize: '6.250rem',
    titleHugeLineHeight: '6.250rem',
    titleBigFontSize: '4.500rem',
    titleBigLineHeight: '4.500rem',
    titleNormalFontSize: '3.750rem',
    titleNormalLineHeight: '3.750rem',
    titleResponsiveFontSize: '2.500rem',
    titleResponsiveLineHeight: '2.500rem',
    titleSmallFontSize: '2.000rem',
    titleSmallLineHeight: '2.000rem',
    titleTinyFontSize: '1.500rem',
    titleTinyLineHeight: '1.500rem',
    paragraphTitleResponsiveFontSize: '1.500rem',
    paragraphTitleResponsiveLineHeight: '2.000rem',
    paragraphHugeFontSize: '1.500rem',
    paragraphHugeLineHeight: '2.000rem',
    paragraphBigFontSize: '1.125rem',
    paragraphBigLineHeight: '1.500rem',
    paragraphNormalFontSize: '1.000rem',
    paragraphNormalLineHeight: '1.500rem',
    paragraphSmallFontSize: '0.875rem',
    paragraphSmallLineHeight: '1.250rem',
    paragraphSmallResponsiveFontSize: '0.875rem',
    paragraphSmallResponsiveLineHeight: '1.250rem',
    paragraphTinyFontSize: '0.750rem',
    paragraphTinyLineHeight: '1.000rem',
    paragraphPrice bubbleLargeFontSize: '2.000rem',
    paragraphPrice bubbleLargeLineHeight: '2.000rem',
    paragraphPrice bubbleSmallFontSize: '1.500rem',
    paragraphPrice bubbleSmallLineHeight: '1.500rem',
    overlineFontSize: '0.875rem',
    overlineLineHeight: '1.000rem',
    fieldInputBigFontSize: '2.000rem',
    fieldInputBigLineHeight: '2.000rem',
    fieldInputFontSize: '1.000rem',
    fieldInputLineHeight: '1.500rem',
    fieldLabelFontSize: '1.000rem',
    fieldLabelLineHeight: '1.500rem',
    fieldHintFontSize: '0.750rem',
    fieldHintLineHeight: '1.000rem',
    linksBigFontSize: '1.500rem',
    linksBigLineHeight: '2.500rem',
    linksNormalFontSize: '1.000rem',
    linksNormalLineHeight: '1.500rem',
    linksSmallFontSize: '0.875rem',
    linksSmallLineHeight: '1.250rem',
    linksTinyFontSize: '0.750rem',
    linksTinyLineHeight: '1.000rem',
    linksFooterFontSize: '0.750rem',
    linksFooterLineHeight: '1.625rem',
  },
};