// component tokens for lloyds

export default {
  button: {
    colourPrimaryBackgroundDefault: '#000000',
    colourPrimaryBackgroundHover: '#323232',
    colourPrimaryBackgroundPressed: '#000000',
    colourPrimaryBackgroundFocus: '#000000',
    colourPrimaryBackgroundDisabled: '#c9c9c9',
    colourPrimaryTextDefault: '#ffffff',
    colourPrimaryTextDisabled: '#767676',
    colourPrimaryBorderFocus: '#000000',
    colourSecondaryBackgroundDefault: '#ffffff',
    colourSecondaryBackgroundHover: '#f1f1f1',
    colourSecondaryBackgroundPressed: '#000000',
    colourSecondaryBackgroundFocus: '#ffffff',
    colourSecondaryBackgroundDisabled: '#c9c9c9',
    colourSecondaryTextDefault: '#000000',
    colourSecondaryTextHover: '#000000',
    colourSecondaryTextDisabled: '#767676',
    colourSecondaryTextPressed: '#ffffff',
    colourSecondaryIconDefault: '#000000',
    colourSecondaryBorderDefault: '#000000',
    colourSecondaryBorderHover: '#323232',
    colourSecondaryBorderFocus: '#000000',
    colourSecondaryBorderFocusInner: '#000000',
    colourTertiaryBackgroundDefault: '#ffffff',
    colourTertiaryBackgroundActive: '#000000',
    colourTertiaryBackgroundInverse: '#ffffff',
    colourTertiaryBorderDefault: '#000000',
    colourTertiaryBorderActive: '#000000',
    radiusDefault: '0.750rem',
    radiusFocus: '1.000rem',
    spaceFocus: '0.313rem',
    sizeSmMinHeight: '3.000rem',
    typeMediumFontSize: '1.063rem',
    typeMediumLineHeight: '1.375rem',
    typeSmallFontSize: '0.938rem',
    typeSmallLineHeight: '1.250rem',
    typeTinyFontSize: '0.750rem',
    typeTinyLineHeight: '1.000rem',
    typeTagFontSize: '0.750rem',
    typeTagLineHeight: '1.000rem',
  },
  card: {
    borderDefault: '0',
    borderInverse: '0.063rem',
    spaceDefault: '1.500rem',
    spaceSmNegative: '0',
    spaceSmPositive: '1.000rem',
  },
  checkbox: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#ffffff',
    colourBackgroundDisabled: '#ffffff',
    colourBackgroundActiveDisabled: '#a8a8a8',
    colourBorderDefault: '#000000',
    colourBorderHover: '#000000',
    colourBorderFocusInner: '#000000',
    colourBorderFocusOuter: '#000000',
    colourBorderDisabled: '#a8a8a8',
    colourBorderDisabled2: '#a8a8a8',
    colourIconDefault: '#000000',
    colourIconDisabled: '#ffffff',
    borderDefault: '0.063rem',
    borderSelected: '0.063rem',
    borderFocusInner: '0.125rem',
    borderFocusOuter: '0.125rem',
    radiusDefault: '0.375rem',
    radiusFocus: '0.500rem',
  },
  chip: {
    colourBackgroundDefault: '#11b67a',
    colourTextDefault: '#000000',
  },
  input: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundDim: '#f1f1f1',
    colourBackgroundHover: '#000000',
    colourBackgroundError: '#fff6f5',
    colourBackgroundDisabled: '#f5f5f5',
    colourBackgroundDisabled2: '#f1f1f1',
    colourTextInverse: '#ffffff',
    colourBorderDefault: '#000000',
    colourBorderSubdued: '#c9c9c9',
    colourBorderActive: '#000000',
    colourBorderDisabled: '#f1f1f1',
    borderDefault: '0.063rem',
    borderActive: '0.125rem',
  },
  label: {
    colourBackgroundDefault: '#6cf479',
    colourTextDefault: '#000000',
  },
  masthead: {
    colourSurfaceBrand: '#11b67a',
    colourSurfaceBrand2: '#ffffff',
    colourSurfaceBrand3: '#ffffff',
    colourSizeHelphubNavHeight: '4.500rem',
  },
  menu: {
    colourBackgroundDefault: '#000000',
    colourTextDefault: '#ffffff',
    colourIconDefault: '#ffffff',
  },
  notification: {
    borderDefault: '0.063rem',
    radiusDefault: '0.750rem',
  },
  panel: {
    radiusDefault: '0',
  },
  progressStep: {
    colourBackgroundDefault: '#f1f1f1',
    colourBackgroundDefault2: '#767676',
    colourBackgroundDefault3: '#ffffff',
    colourBackgroundActive: '#10a870',
    colourBackgroundDashedLine: '#767676',
    colourTextComplete: '#000000',
    colourTextCurrent: '#000000',
    colourTextRemaining: '#767676',
    borderMojaLbg: '0.063rem',
    borderInner: '0.375rem',
  },
  radio: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#000000',
    colourBackgroundDisabled: '#a8a8a8',
    colourRadioDefault: '#000000',
    colourRadioHover: '#000000',
    colourRadioFocusInner: '#000000',
    colourRadioFocusOuter: '#000000',
    colourRadioDisabled: '#c9c9c9',
    colourRadioActiveDisabled: '#a8a8a8',
    borderDefault: '0.063rem',
    borderSelected: '0.063rem',
    borderFocusInner: '0.125rem',
    borderFocusOuter: '0.125rem',
  },
  selector: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#f1f1f1',
    colourBackgroundActive: '#ffffff',
    colourBackgroundActiveDisabled: '#f5f5f5',
    colourBackgroundDisabled: '#f5f5f5',
    colourTextDefault: '#000000',
    colourTextActive: '#000000',
    colourTextDisabled: '#a8a8a8',
    colourBorderDefault: '#ffffff',
    colourBorderDefault2: '#a8a8a8',
    colourBorderBrand: '#11b67a',
    colourBorderCurrent: '#c0c0c0',
    colourBorderDisabled: '#f5f5f5',
    colourBorderActive: '#000000',
    colourBorderActiveDisabled: '#a8a8a8',
    borderDefault: '0.125rem',
    borderDefaultInverse: '0',
    borderUnselected: '0.063rem',
    typeSelector text: 'Regular',
  },
  switch: {
    colourBackgroundInverse: '#ffffff',
    colourBackgroundBrand: '#000000',
    colourBackgroundSwitchOff: '#000000',
    colourBackgroundBackgroundOff: '#ffffff',
    colourBackgroundDisabled: '#f5f5f5',
    colourBackgroundActiveDisabled: '#c0c0c0',
  },
  table: {
    colourBackgroundFixed: '#ffffff',
    colourBackgroundFixedSubtle: '#f1f1f1',
    colourBackgroundHeader: '#323232',
    colourBackgroundActive: '#000000',
    colourBackgroundActiveSubdued: '#c7ffc6',
    colourBackgroundActiveSubtle: '#ffffff',
    colourTextDefault: '#000000',
    colourTextHeader: '#ffffff',
    colourTextInverse: '#ffffff',
    colourTextActive: '#000000',
    colourBorderDefault1: '#000000',
    colourBorderDefault2: '#767676',
    colourBorderBrand: '#11b67a',
    colourBorderActive: '#000000',
  },
  tile: {
    sizeMinHeight: '12.625rem',
  },
  toggle: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundActive: '#000000',
    colourTextDefault: '#000000',
    colourTextActive: '#ffffff',
    colourBorderDefault: '#000000',
    borderOuter: '0.063rem',
    borderOuterNone: '0',
    borderInner: '0',
    radiusInner: '0',
    radiusOuter: '0.750rem',
    spaceDefault: '0',
    typeToggle: 'Regular',
  },
};