// component tokens for bos

export default {
  button: {
    colourPrimaryBackgroundDefault: '#005ba2',
    colourPrimaryBackgroundHover: '#05286a',
    colourPrimaryBackgroundPressed: '#05286a',
    colourPrimaryBackgroundFocus: '#05286a',
    colourPrimaryBackgroundDisabled: '#f1f1f1',
    colourPrimaryTextDefault: '#ffffff',
    colourPrimaryTextDisabled: '#767676',
    colourPrimaryBorderFocus: '#00084d',
    colourSecondaryBackgroundDefault: '#ffffff',
    colourSecondaryBackgroundHover: '#f1f1f1',
    colourSecondaryBackgroundPressed: '#005ba2',
    colourSecondaryBackgroundFocus: '#ffffff',
    colourSecondaryBackgroundDisabled: '#adadad',
    colourSecondaryTextDefault: '#005ba2',
    colourSecondaryTextHover: '#00084d',
    colourSecondaryTextDisabled: '#767676',
    colourSecondaryTextPressed: '#ffffff',
    colourSecondaryIconDefault: '#05286a',
    colourSecondaryBorderDefault: '#05286a',
    colourSecondaryBorderHover: '#05286a',
    colourSecondaryBorderFocus: '#005ba2',
    colourSecondaryBorderFocusInner: '#005ba2',
    colourTertiaryBackgroundDefault: '#ffffff',
    colourTertiaryBackgroundActive: '#05286a',
    colourTertiaryBackgroundInverse: '#ffffff',
    colourTertiaryBorderDefault: '#005ba2',
    colourTertiaryBorderActive: '#05286a',
    radiusDefault: '0',
    radiusFocus: '0',
    spaceFocus: '0.313rem',
    sizeSmMinHeight: '3.000rem',
    typeMediumFontSize: '1.125rem',
    typeMediumLineHeight: '1.438rem',
    typeSmallFontSize: '1.000rem',
    typeSmallLineHeight: '1.250rem',
    typeTinyFontSize: '0.750rem',
    typeTinyLineHeight: '1.000rem',
    typeTagFontSize: '0.750rem',
    typeTagLineHeight: '1.000rem',
  },
  card: {
    borderDefault: '0',
    borderInverse: '0.063rem',
    spaceDefault: '1.500rem',
    spaceSmNegative: '0',
    spaceSmPositive: '1.000rem',
  },
  checkbox: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#ffffff',
    colourBackgroundDisabled: '#ffffff',
    colourBackgroundActiveDisabled: '#f1f1f1',
    colourBorderDefault: '#505050',
    colourBorderHover: '#05286a',
    colourBorderFocusInner: '#05286a',
    colourBorderFocusOuter: '#05286a',
    colourBorderDisabled: '#767676',
    colourBorderDisabled2: '#adadad',
    colourIconDefault: '#005ba2',
    colourIconDisabled: '#adadad',
    borderDefault: '0.063rem',
    borderSelected: '0.125rem',
    borderFocusInner: '0.063rem',
    borderFocusOuter: '0.125rem',
    radiusDefault: '0',
    radiusFocus: '0',
  },
  chip: {
    colourBackgroundDefault: '#05286a',
    colourTextDefault: '#ffffff',
  },
  input: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundDim: '#f1f1f1',
    colourBackgroundHover: '#767676',
    colourBackgroundError: '#fef6f8',
    colourBackgroundDisabled: '#f1f1f1',
    colourBackgroundDisabled2: '#f1f1f1',
    colourTextInverse: '#ffffff',
    colourBorderDefault: '#505050',
    colourBorderSubdued: '#adadad',
    colourBorderActive: '#505050',
    colourBorderDisabled: '#f1f1f1',
    borderDefault: '0.063rem',
    borderActive: '0.063rem',
  },
  label: {
    colourBackgroundDefault: '#157eb3',
    colourTextDefault: '#ffffff',
  },
  masthead: {
    colourSurfaceBrand: '#05286a',
    colourSurfaceBrand2: '#f2f6fa',
    colourSurfaceBrand3: '#05286a',
    colourSizeHelphubNavHeight: '4.500rem',
  },
  menu: {
    colourBackgroundDefault: '#f2f6fa',
    colourTextDefault: '#05286a',
    colourIconDefault: '#05286a',
  },
  notification: {
    borderDefault: '0',
    radiusDefault: '0',
  },
  panel: {
    radiusDefault: '0',
  },
  progressStep: {
    colourBackgroundDefault: '#f1f1f1',
    colourBackgroundDefault2: '#adadad',
    colourBackgroundDefault3: '#ffffff',
    colourBackgroundActive: '#047457',
    colourBackgroundDashedLine: '#767676',
    colourTextComplete: '#000000',
    colourTextCurrent: '#05286a',
    colourTextRemaining: '#767676',
    borderMojaLbg: '0.063rem',
    borderInner: '0.375rem',
  },
  radio: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#005ba2',
    colourBackgroundDisabled: '#adadad',
    colourRadioDefault: '#505050',
    colourRadioHover: '#00084d',
    colourRadioFocusInner: '#333333',
    colourRadioFocusOuter: '#00084d',
    colourRadioDisabled: '#505050',
    colourRadioActiveDisabled: '#767676',
    borderDefault: '0.063rem',
    borderSelected: '0.063rem',
    borderFocusInner: '0.063rem',
    borderFocusOuter: '0.125rem',
  },
  selector: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundHover: '#f1f1f1',
    colourBackgroundActive: '#ffffff',
    colourBackgroundActiveDisabled: '#f2f6fa',
    colourBackgroundDisabled: '#f1f1f1',
    colourTextDefault: '#005ba2',
    colourTextActive: '#05286a',
    colourTextDisabled: '#767676',
    colourBorderDefault: '#505050',
    colourBorderDefault2: '#505050',
    colourBorderBrand: '#05286a',
    colourBorderCurrent: '#adadad',
    colourBorderDisabled: '#505050',
    colourBorderActive: '#05286a',
    colourBorderActiveDisabled: '#005ba2',
    borderDefault: '0.125rem',
    borderDefaultInverse: '0',
    borderUnselected: '0.063rem',
    typeSelector text: 'Demi',
  },
  switch: {
    colourBackgroundInverse: '#ffffff',
    colourBackgroundBrand: '#005ba2',
    colourBackgroundSwitchOff: '#ffffff',
    colourBackgroundBackgroundOff: '#767676',
    colourBackgroundDisabled: '#f1f1f1',
    colourBackgroundActiveDisabled: '#f2f6fa',
  },
  table: {
    colourBackgroundFixed: '#ffffff',
    colourBackgroundFixedSubtle: '#ffffff',
    colourBackgroundHeader: '#f2f6fa',
    colourBackgroundActive: '#005ba2',
    colourBackgroundActiveSubdued: '#f2f6fa',
    colourBackgroundActiveSubtle: '#f2f6fa',
    colourTextDefault: '#000000',
    colourTextHeader: '#00084d',
    colourTextInverse: '#ffffff',
    colourTextActive: '#000000',
    colourBorderDefault1: '#005ba2',
    colourBorderDefault2: '#333333',
    colourBorderBrand: '#005ba2',
    colourBorderActive: '#005ba2',
  },
  tile: {
    sizeMinHeight: '12.625rem',
  },
  toggle: {
    colourBackgroundDefault: '#ffffff',
    colourBackgroundActive: '#05286a',
    colourTextDefault: '#005ba2',
    colourTextActive: '#ffffff',
    colourBorderDefault: '#767676',
    borderOuter: '0.063rem',
    borderOuterNone: '0',
    borderInner: '0',
    radiusInner: '0',
    radiusOuter: '0',
    spaceDefault: '0',
    typeToggle: 'Demi',
  },
};