// typography tokens for bos

export default {
  font: {
    familyPrimary: 'BoS Pill Gothic',
    familySecondary: 'Avenir Next LT Pro',
    weightHeadingPrimary: 'Demi',
    weightBodyPrimary: 'Regular',
    weightBodyAlt1: 'Demi',
    weightBodyAlt2: 'Bold',
  },
  textStyle: {
    titleFontSize: '1.250rem',
    titleLineHeight: '1.250rem',
    titleHugeFontSize: '2.500rem',
    titleHugeLineHeight: '2.750rem',
    titleBigFontSize: '2.500rem',
    titleBigLineHeight: '2.750rem',
    titleNormalFontSize: '2.500rem',
    titleNormalLineHeight: '2.750rem',
    titleResponsiveFontSize: '1.813rem',
    titleResponsiveLineHeight: '2.000rem',
    titleSmallFontSize: '1.813rem',
    titleSmallLineHeight: '2.000rem',
    titleTinyFontSize: '1.438rem',
    titleTinyLineHeight: '1.500rem',
    paragraphTitleResponsiveFontSize: '1.438rem',
    paragraphTitleResponsiveLineHeight: '1.625rem',
    paragraphHugeFontSize: '1.438rem',
    paragraphHugeLineHeight: '1.625rem',
    paragraphBigFontSize: '1.188rem',
    paragraphBigLineHeight: '1.375rem',
    paragraphNormalFontSize: '1.000rem',
    paragraphNormalLineHeight: '1.250rem',
    paragraphSmallFontSize: '0.875rem',
    paragraphSmallLineHeight: '1.250rem',
    paragraphSmallResponsiveFontSize: '0.875rem',
    paragraphSmallResponsiveLineHeight: '1.250rem',
    paragraphTinyFontSize: '0.750rem',
    paragraphTinyLineHeight: '1.000rem',
    paragraphPrice bubbleLargeFontSize: '1.375rem',
    paragraphPrice bubbleLargeLineHeight: '2.000rem',
    paragraphPrice bubbleSmallFontSize: '1.438rem',
    paragraphPrice bubbleSmallLineHeight: '1.500rem',
    overlineFontSize: '1.000rem',
    overlineLineHeight: '1.000rem',
    fieldInputBigFontSize: '2.000rem',
    fieldInputBigLineHeight: '2.000rem',
    fieldInputFontSize: '1.000rem',
    fieldInputLineHeight: '1.250rem',
    fieldLabelFontSize: '1.000rem',
    fieldLabelLineHeight: '1.250rem',
    fieldHintFontSize: '0.750rem',
    fieldHintLineHeight: '1.000rem',
    linksBigFontSize: '1.438rem',
    linksBigLineHeight: '1.625rem',
    linksNormalFontSize: '1.000rem',
    linksNormalLineHeight: '1.250rem',
    linksSmallFontSize: '0.875rem',
    linksSmallLineHeight: '1.250rem',
    linksTinyFontSize: '0.750rem',
    linksTinyLineHeight: '1.000rem',
    linksFooterFontSize: '0.875rem',
    linksFooterLineHeight: '1.625rem',
  },
};